version: '3'

services:
  ephor.com.br:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=production.settings
    command: gunicorn --bind 0.0.0.0:8000 production.wsgi:application
    dns:
      - 1.1.1.1
      - 1.0.0.1
    extra_hosts:
      - "ephor.com.br:127.0.0.1"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
        labels: "production_logs"
volumes:
  static_volume:
  media_volume:
