version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: gunicorn -c gunicorn.conf production.wsgi:application
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydatabasename
      MYSQL_USER: mydatabaseuser
      MYSQL_PASSWORD: mydatabasepassword
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
      - "8081:443"
    depends_on:
      - web

volumes:
  mysql_data:
