# Generated by Django 4.1 on 2022-09-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpost_publish_date_alter_blogpost_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', 'updated', '-timestamp']},
        ),
    ]
