# Generated by Django 4.1 on 2022-09-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pk', '-publish_date', 'updated', '-timestamp']},
        ),
    ]
