# Generated by Django 4.1 on 2022-09-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='barplot',
            field=models.ImageField(blank=True, null=True, upload_to='image/plots/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='wordcloud',
            field=models.ImageField(blank=True, null=True, upload_to='image/plots/'),
        ),
    ]
