# Generated by Django 4.1 on 2022-09-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blogpost_barplot_blogpost_wordcloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summ_bert',
            field=models.TextField(blank=True, null=True),
        ),
    ]
