# Generated by Django 4.1 on 2022-09-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_blogpost_article_blogpost_maltego_csv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='barplot',
            field=models.FilePathField(blank=True, null=True, path='image/plots/barplots'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='maltego_csv',
            field=models.FilePathField(blank=True, null=True, path='image/plots/maltego_csv'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='wordcloud',
            field=models.FilePathField(blank=True, null=True, path='image/plots/wordclouds'),
        ),
    ]
