# Generated by Django 4.1 on 2022-09-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_blogpost_barplot_alter_blogpost_maltego_csv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='barplot',
            field=models.FileField(blank=True, null=True, upload_to='image/plots/barplots/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='maltego_csv',
            field=models.FileField(blank=True, null=True, upload_to='image/plots/maltego_csv/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='wordcloud',
            field=models.FileField(blank=True, null=True, upload_to='image/plots/wordclouds/'),
        ),
    ]
