# Generated by Django 4.1 on 2022-09-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_blogpost_barplot_alter_blogpost_maltego_csv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pdfs',
            field=models.FileField(blank=True, null=True, upload_to='image/plots/out_pdf/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='barplot',
            field=models.ImageField(blank=True, null=True, upload_to='image/plots/barplots/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='wordcloud',
            field=models.ImageField(blank=True, null=True, upload_to='image/plots/wordclouds/'),
        ),
    ]
