# Generated by Django 4.1 on 2022-09-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_blogpost_pdfs_alter_blogpost_barplot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='article',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='barplot',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='maltego_csv',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='pdfs',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='rainette_explor',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='summ_bert',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='wordcloud',
        ),
    ]
