# Generated by Django 4.1 on 2022-09-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_blogpost_article_remove_blogpost_barplot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='article',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='barplot',
            field=models.ImageField(blank=True, null=True, upload_to='image/plots/barplots/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='maltego_csv',
            field=models.FileField(blank=True, null=True, upload_to='image/plots/maltego_csv/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pdfs',
            field=models.FileField(blank=True, null=True, upload_to='image/plots/out_pdf/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='rainette_explor',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='summ_bert',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='wordcloud',
            field=models.ImageField(blank=True, null=True, upload_to='image/plots/wordclouds/'),
        ),
    ]
