# Generated by Django 4.1 on 2022-09-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_blogpost_article_blogpost_barplot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='sents_1',
            field=models.FileField(blank=True, null=True, upload_to='image/plots/sents_1/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sents_2',
            field=models.FileField(blank=True, null=True, upload_to='image/plots/sents_2/'),
        ),
    ]
