# Generated by Django 4.1 on 2022-09-22 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_blogpost_sents_1_blogpost_sents_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='sents_2',
        ),
    ]
