# Generated by Django 4.1 on 2022-09-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_remove_blogpost_sents_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='reinert',
            field=models.FileField(blank=True, null=True, upload_to='image/plots/reinerts/'),
        ),
    ]
