# Generated by Django 4.1 on 2022-10-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_blogpost_reinert'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='barplot_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='plot_min_freq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reinert_k',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reinert_min_freq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reinert_min_seg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reinert_segm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
