# Generated by Django 4.1 on 2022-10-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_blogpost_barplot_size_blogpost_plot_min_freq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='alt_freq_alt_ord',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='alt_freq_bai_ord',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='bai_freq_alt_ord',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='bai_freq_bai_ord',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='output_bi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='output_tri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
