# Generated by Django 4.1 on 2022-10-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_blogpost_alt_freq_alt_ord_blogpost_alt_freq_bai_ord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='ent_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
