# Generated by Django 4.1 on 2022-10-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_blogpost_ent_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='ent_list',
            new_name='ent_list_fin',
        ),
    ]
