# Generated by Django 4.1 on 2022-10-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_rename_ent_list_blogpost_ent_list_fin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='ent_list_fin',
            new_name='ent_list',
        ),
    ]
