# Generated by Django 4.2.5 on 2023-09-29 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_remove_useraccesslog_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccesslog',
            name='external_ip',
        ),
        migrations.RemoveField(
            model_name='useraccesslog',
            name='internal_ip',
        ),
    ]
